name: Run Checks
description: Lint, type-check & build
runs:
  using: 'composite'
  steps:
    - name: Lint
      run: npm run lint
      shell: bash
    - name: Type Check
      run: npm run type-check
      shell: bash
    - name: Build
      run: npm run package
      shell: bash
