name: Run Checks
description: Install NPM dependencies, Lint, TypeCheck & Build

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        cache: 'npm'
    - name: Install Packages (npm ci)
      run: npm ci
      shell: bash
    - name: Lint
      run: npm run lint
      shell: bash
    - name: Type Check
      run: npm run type-check
      shell: bash
    - name: Build
      run: npm run package
      shell: bash
