// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#xQQOPOOOVOPO'#C^O[OPO'#CeQQOPOOOaOPO,58xOlOPO'#CdOzOPO'#CdOOOO,59P,59POOOO-E6c-E6cOOOO'#Cg'#CgO!POPO'#CbO!XOPO'#CfO!^OPO'#CaO!iOPO1G.dOOOO,59S,59SO!nOPO,59OOOOO-E6f-E6fOOOO-E6e-E6eOOOO,59Q,59QOOOO-E6d-E6dOOOO7+$O7+$OP!|OPO'#Ch",
  stateData: "#Z~ORPO~OSSO~OSTO~OVXORTPSUP~OVXORWXSUP]WX~OS_O~OVXOSUX~OSbO~OVXORTXSUP~ORdO~OVXORWaSUP]Wa~OVXOSUP~ORSVS~",
  goto: "!_]PP^PPbePnqw}!XTQORR]SSZS[V^T_eRVQQRORWRQ[SRc[YYST[_eRaYQUQR`U",
  nodeNames: "⚠ T YamlBlock Delimiter Break YamlContent Content Any MarkdownBlock",
  maxTerm: 13,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "!]~RVOYhYZmZ}h}!Or!O;'Sh;'S;=`!V<%lOh~mOV~~rOS~~wPV~}!Oz~}P}!O!Q~!VOR~~!YP;=`<%lh",
  tokenizers: [0],
  topRules: {"T":[0,1]},
  tokenPrec: 98
})
