// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  T = 1,
  YamlBlock = 2,
  DelimiterStartLine = 3,
  StartDelimiter = 4,
  Delimiter = 5,
  AnyContentLine = 6,
  Any = 7,
  Break = 8,
  YamlContent = 9,
  NoDelimiterStartLine = 10,
  MarkdownContent = 11
