// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  T = 1,
  YamlBlock = 2,
  Delimiter = 3,
  Break = 4,
  YamlContent = 5,
  Content = 6,
  Any = 7,
  MarkdownBlock = 8
