name: Configure
description: Configure the environment & install NPM dependencies
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        cache: '' # disable cache, as it sometimes causes issues with file not being found
    - name: Install Packages (npm ci)
      run: npm ci
      shell: bash
