name: Configure
description: Configure the environment & install NPM dependencies
runs:
  using: 'composite'
  steps:
    - name: Install Packages (npm ci)
      run: npm ci
      shell: bash
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '19.6'
        # cache: 'npm'
