name: Configure
description: Configure the environment & install NPM dependencies
runs:
  using: 'composite'
  steps:
    - name: Install Packages (npm ci)
      run: npm install
      shell: bash
    - name: Electron Rebuild
      run: ./node_modules/.bin/electron-rebuild
      shell: bash
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        cache: 'npm'
