name: Configure
description: Configure the environment
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        cache: 'npm'
