stylesheets:
    - ./reveal_js/dist/reveal.css
    - ./styles/black.css
    - ./styles/custom.css
plugins:
    - ./reveal_js/dist/reveal.js
    - ./reveal_js/plugin/markdown/markdown.js
    - ./reveal_js/plugin/highlight/highlight.js
    - ./reveal_js/plugin/notes/notes.js
    - ./menu/menu.js
entry: ./custom.js
slide: ./slide.html
