# Entry point script which must call `RevealEditor.configure()`.
entry: ./index.js
# Entry point script and stylesheet(s) of the reveal.js distribution.
reveal:
  entry: ./reveal_js/dist/reveal.js
  stylesheets: ./reveal_js/dist/reveal.css
# Additional stylesheets which are loaded after reveal and theme stylesheets.
stylesheets: 
  - ./styles/reveal.css
  - ./styles/layouts.css
  - ./styles/image.css
  - ./styles/text.css
  - ./styles/background.css
  - ./styles/margin.css
  - ./styles/size.css
  - ./styles/code.css
  - ./styles/space.css
  - ./styles/fragment.css
  - ./styles/print.css
# Additional scripts which are loaded after the reveal entry script, but before the entry script
# This property is suitable to specify additional (reveal.js) plugins.
scripts:
  - ./reveal_js/plugin/highlight/highlight.js
  - ./reveal_js/plugin/math/math.js
  - ./reveal_js/plugin/search/search.js
  - ./reveal_js/plugin/zoom/zoom.js
  - ./reveal_js/plugin/notes/notes.js
# HTML file which allows to define a wrapper around all slides.
# Must contain a `@@content@@` token where the slide content will be placed.
slide: ./slide.html
# Definition of themes which add additional stylesheets.
themes:
  - name: black
    default: true
    stylesheets:
      - ./reveal_js/dist/theme/black.css
      - ./styles/colors/black.css
      - ./styles/code/stackoverflow-dark.css
  - name: white
    stylesheets:
      - ./reveal_js/dist/theme/white.css
      - ./styles/colors/white.css
      - ./styles/code/stackoverflow-light.css
# Definition of layouts which are used to build the slides.
# Every layout must contain at least one `@@slot@@` token where the content is placed.
layouts:
  - name: base
    default: true
    path: ./layouts/base.html
  - name: cols-2
    path: ./layouts/cols-2.html
  - name: cols-3
    path: ./layouts/cols-3.html
  - name: cols-4
    path: ./layouts/cols-4.html
  - name: grid-3
    path: ./layouts/grid-3-left.html
  - name: grid-3-right
    path: ./layouts/grid-3-right.html
  - name: grid-4
    path: ./layouts/grid-4.html
  - name: grid-5
    path: ./layouts/grid-5.html
  - name: grid-6
    path: ./layouts/grid-6.html
  - name: grid-7
    path: ./layouts/grid-7.html
  - name: grid-8
    path: ./layouts/grid-8.html
  - name: grid-9
    path: ./layouts/grid-9.html
  - name: title-content
    path: ./layouts/title-content.html
  - name: title-cols-2
    path: ./layouts/title-cols-2.html
  - name: title-cols-3
    path: ./layouts/title-cols-3.html
  - name: title-grid-3
    path: ./layouts/title-grid-3-left.html
  - name: title-grid-3-right
    path: ./layouts/title-grid-3-right.html
  - name: title-grid-4
    path: ./layouts/title-grid-4.html
# For every section of the toolbar a separate file can be specified
# which lists all items to show in this section
toolbar:
  layouts: ./toolbar/layouts.yml
  styles: ./toolbar/styles.yml
  animation: ./toolbar/animation.yml
  slide: ./toolbar/slide.yml
  slideStyles: ./toolbar/slideStyles.yml
