entry: ./index.js
reveal: ./reveal_js/dist/reveal.js
presentation: ./presentation.html
stylesheets:
  - ./reveal_js/dist/reveal.css
  - ./reveal_js/plugin/highlight/monokai.css
  - ./index.css
  - ./layouts/index.css
plugins:
  - ./reveal_js/plugin/highlight/highlight.js
  - ./reveal_js/plugin/math/math.js
themes: 
  - name: black
    default: true
    stylesheets: 
      - ./reveal_js/dist/theme/black.css
  - name: white
    stylesheets: 
      - ./reveal_js/dist/theme/white.css
  - name: beige
    stylesheets: 
      - ./reveal_js/dist/theme/beige.css
layouts: 
  - name: base
    default: true
    path: ./layouts/base.html
  - name: cols-2
    path: ./layouts/cols-2.html
  - name: cols-3
    path: ./layouts/cols-3.html
  - name: cols-4
    path: ./layouts/cols-4.html
  - name: grid-3
    path: ./layouts/grid-3-left.html
  - name: grid-3-right
    path: ./layouts/grid-3-right.html
  - name: grid-4
    path: ./layouts/grid-4.html
  - name: grid-5
    path: ./layouts/grid-5.html
  - name: grid-6
    path: ./layouts/grid-6.html
  - name: grid-7
    path: ./layouts/grid-7.html
  - name: grid-8
    path: ./layouts/grid-8.html
  - name: grid-9
    path: ./layouts/grid-9.html
  - name: title-cols-2
    path: ./layouts/title-cols-2.html
  - name: title-cols-3
    path: ./layouts/title-cols-3.html
  - name: title-grid-3
    path: ./layouts/title-grid-3-left.html
  - name: title-grid-3-right
    path: ./layouts/title-grid-3-right.html
  - name: title-grid-4
    path: ./layouts/title-grid-4.html
  