name: Checks

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  check:
    name: ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
      - name: Install Packages (npm ci)
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Build
        run: npm run package
