name: Run CI/CD
on:
  push:
    # tags:
    #   - v*
    branches-ignore:
      - 'main'
  workflow_dispatch:
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  deploy:
    name: Run Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        uses: ./.github/actions/configure
      - name: Run Checks
        uses: ./.github/actions/check
      - name: Publish
        uses: ./.github/actions/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          os: ${{ matrix.os }}
