name: Run CI/CD
on:
  push:
    # tags:
    #   - v*
    branches-ignore:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Run Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        uses: ./.github/actions/configure
      - name: Run Checks
        uses: ./.github/actions/check
      - name: Publish
        uses: ./.github/actions/publish
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
