name: Run CI/CD
on:
  push:
    # tags:
    #   - v*
    branches-ignore:
      - 'main'
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  deploy:
    name: Run Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        uses: ./.github/actions/configure
      # - name: Run Checks
      #   uses: ./.github/actions/check
      - name: Publish
        uses: ./.github/actions/publish
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
