name: Run CI/CD
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  deploy:
    name: Run Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        uses: ./.github/actions/configure
      - name: Run Checks
        uses: ./.github/actions/check
      - name: Publish
        uses: ./.github/actions/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          os: ${{ matrix.os }}
