name: Run CI
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  check:
    name: Run Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        uses: ./.github/actions/configure
      - name: Run Checks
        uses: ./.github/actions/check
      - name: Publish
        uses: ./.github/actions/publish
