name: Run Checks

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check:
    name: Run Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Run Prepare
        uses: ./.github/actions/prepare
      - name: Run Checks
        uses: ./.github/actions/check
