name: Run Checks

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check:
    name: Run Checks
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    uses: ./.github/workflows/check.yml
    with:
      os: ${{ matrix.os }}
